CUTOFF = 0.85
X_DIM = 10
Y_DIM = 10
Z_DIM = 10
'''
with open("test.pdb", "w") as file:
    file.write("HEADER    Test\n")
    file.write("CRYST1   2.5500   2.5500   2.5500  90.00  90.00  90.00 P 1           1\n")
    pcnt = 0
    # Write a line to the file
    for i in range(X_DIM*4):
      for j in range(Y_DIM*4):
        for k in range(Z_DIM*4):
          pcnt += 1
          file.write("ATOM      "+str(pcnt)+"  Na  ABC      "+str(round(CUTOFF/8+CUTOFF/4*i,3))+"      "+str(round(CUTOFF/8+CUTOFF/4*j,3))+"      "+str(round(CUTOFF/8+CUTOFF/4*k,3))+"      1.00  0.00\n")
'''

with open('test_aaa.pdb', 'w') as f:
  pcnt = 0
  # Write the header information
  f.write('REMARK   1 GENERATED BY PYTHON\n')
  f.write('TITLE    NA ATOMS IN VACUUM\n')
  f.write("CRYST1  8.5000   8.5000   8.5000   90.00  90.00   90.00 P 1           1\n")

  # Loop through 100 times to write 100 sodium atoms
  for i in range(X_DIM*4):
    for j in range(Y_DIM*4):
      for k in range(Z_DIM*4):
        pcnt += 1
        # Generate random x, y, z coordinates
        x = CUTOFF/8+CUTOFF/4*i
        y = CUTOFF/8+CUTOFF/4*j
        z = CUTOFF/8+CUTOFF/4*k
  
        # Write the ATOM record
        f.write(f'ATOM  {pcnt:>5}  Na  ABC {pcnt:>5} {x:>8.3f}  {y:>8.3f}  {z:>8.3f}      1.00  0.00\n')

  # Write the END record
  f.write('END\n')

print('PDB file generated successfully!')